version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  nodejs:
    build: .
    env_file: ./.env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: $MYSQL_USER
      DB_PASSWORD: $MYSQL_ROOT_PASSWORD
      DB_NAME: $MYSQL_DATABASE
      DB_PORT: $MYSQLDB_DOCKER_PORT
      

volumes: 
  db:
